#!/bin/bash
certfile=$(ls  --sort=time --reverse ~/Downloads/avans*.ovpn | tail -n 1)


noAfter=$(date -d "$(cat "${certfile}" | sed -n '/<cert>/,/<\/cert>/p' | grep -v 'cert>' | openssl x509 -in - -noout -enddate | sed 's/notAfter=//g')" "+%s")
now=$(date "+%s")
expiresIn=$(( noAfter - now ))

#if (( expiresIn < 0 )); then
	#echo "Cert expired, refresh it please."
	#exit 1
#fi

#if (( expiresIn < 28800 )); then
	#echo "Cert expires in less than 8 hours"
	#sleep 0.5
#fi

expiresInHours=$(echo "$expiresIn / 3600" | bc -l)

echo "Cert expires in $expiresInHours hours"
sudo openvpn "${certfile}"
