#!/bin/bash
SERVER=$1
PORT=${2:-443}

if [[ -f "${SERVER}" ]]; then
	openssl crl2pkcs7 -nocrl -certfile "${SERVER}" | \
		openssl pkcs7 -print_certs -text -noout
else
	openssl crl2pkcs7 -nocrl -certfile <( echo '' | openssl s_client -connect ${SERVER}:${PORT} -showcerts 2>/dev/null) | \
		openssl pkcs7 -print_certs -text -noout
fi
