#!/bin/bash
URL=rtmp://a.rtmp.youtube.com/live2
KEY=

ffmpeg -f alsa -ac 2 -i hw:0,0 -f v4l2 -s 1920x1080 -r 10 -i /dev/video0 -vcodec libx264 -pix_fmt yuv420p -preset ultrafast -r 25 -g 20 -b:v 2500k -codec:a libmp3lame -ar 44100 -threads 6 -b:a 11025 -bufsize 512k -f flv $URL/$KEY

